### ISSUE TITLE
Stage channel tracker

### ISSUE THREAD

**Issue by Azn9** [Azn9/Discord4J#1]
- [x] Start stage event (topic, privacy level & notification)
- [x] Get speakers
- [x] Check if a member is a speaker
~~- [ ] Enable/Disable talk requests from everyone~~ (permissions)
- [x] Self move to audience / stage
- [x] Move other to audience
- [x] Invite other to speak
- [x] List speak request
- [x] Accept/Deny speak request
- [x] Self request to speak
- [x] End stage

**Comment by Azn9** [comment]
Keep an eye on state visibility update
https://discord.com/blog/whats-next-for-communities-at-discord
